#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
           fakeroot kmod cpio bc zip git python3-docutils gettext automake autopoint \
           texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
           libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin golang nodejs 
    - name: Clone source code
      run: |
        git clone https://github.com/tsl0922/padavan.git /opt/padavan
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: K2P
      run: |
        cd /opt/padavan
        sudo make K2P-USB
        sudo mv -f images/*.trx /opt/images/
        sudo mv -f trunk/images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
